name: Nightly Build

on:
  schedule:
  # NOTE - changes to the cron spec should be pushed by https://github.com/quic-yocto-ci
  # so that build notification emails will be sent out properly.
  - cron: "23 1 * * *"   # daily job - pick a random "minute"  - top of hour can be busy in github

jobs:
  nightly:
    uses: ./.github/workflows/build-yocto.yml
